// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var url;
    alert("go");
    url = "https://docs.google.com/spreadsheets/d/1vqUYVlWQfEzNlwqrLlpUhqU9RfU45VhQJtietxAsHfg/pub?output=csv";
    return $.ajax({
      type: "GET",
      url: url,
      dataType: "text",
      success: function(data) {
        return console.log(data);
      }
    });
  });

}).call(this);
